apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
  labels:
    app: nginx
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data

