apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: nginx
  labels:
    app: nginx
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
