apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apache-rolebinding
  namespace: apache
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: apache-user
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: apache-role
